apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple
spec:
  replicas: 2
  template:
    spec:
      containers:
      - image: quay.io/wpernath/simple-quarkus:stage
        imagePullPolicy: Always
        name: staging-simple
        ports:
          - containerPort: 8080
            protocol: TCP
        env:
          - name: APP_GREETING
            value: 'Hey, this is the STAGING environment of the App'
