apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple
spec:
  replicas: 1
  template:
    spec:
      containers:
      - image: quay.io/wpernath/simple-quarkus:latest
        imagePullPolicy: Always
        name: dev-simple
        ports:
          - containerPort: 8080
            protocol: TCP
        env:
          - name: APP_GREETING
            value: 'Hey, this is the DEVELOPMENT environment of the App'
  
